// School brand colors keyed by the EXACT name shown in the UI.
// Source: each school's official athletics site.
// To add a new school: just add a new entry. No database, no migrations.

export const SCHOOL_COLORS = {
  // ===== Top 100 D1 women's soccer programs =====
  "Air Force Academy": { primary: "#003087", secondary: "#B0B7BC" },
  "Academy of Art University": { primary: "#000000", secondary: "#A6192E" },
  "Adams State University": { primary: "#1B453E", secondary: "#FFFFFF" },
  "Alabama": { primary: "#9E1B32", secondary: "#828A8F" },
  "Arizona State University": { primary: "#8C1D40", secondary: "#FFC627" },
  "Arkansas": { primary: "#9D2235", secondary: "#FFFFFF" },
  "Auburn": { primary: "#0C2340", secondary: "#E87722" },
  "Azusa Pacific University": { primary: "#000000", secondary: "#A50000" },
  "Baylor": { primary: "#003015", secondary: "#FFB81C" },
  "Biola University": { primary: "#990000", secondary: "#000000" },
  "Boise State University": { primary: "#0033A0", secondary: "#D64309" },
  "Boston College": { primary: "#8C2232", secondary: "#B29D6C" },
  "Brigham Young University": { primary: "#002E5D", secondary: "#FFFFFF" },
  "Brown University": { primary: "#4E3629", secondary: "#ED1C24" },
  "BYU": { primary: "#002E5D", secondary: "#FFFFFF" },
  "California Baptist University": { primary: "#00205B", secondary: "#A39265" },
  "California Institute of Technology": { primary: "#FF6C0C", secondary: "#000000" },
  "California Lutheran University": { primary: "#582C83", secondary: "#FFC72C" },
  "California Polytechnic State University": { primary: "#154734", secondary: "#BD8B13" },
  "California State Polytechnic University, Pomona": { primary: "#1E5631", secondary: "#FFC72C" },
  "California State University, Bakersfield": { primary: "#003594", secondary: "#FFC72C" },
  "California State University, Chico": { primary: "#A91D33", secondary: "#FFFFFF" },
  "California State University, Dominguez Hills": { primary: "#A6192E", secondary: "#FFC72C" },
  "California State University, East Bay": { primary: "#C8102E", secondary: "#000000" },
  "California State University, Fresno": { primary: "#DB0032", secondary: "#013466" },
  "California State University, Fullerton": { primary: "#003366", secondary: "#FF8C00" },
  "California State University, Long Beach": { primary: "#000000", secondary: "#FFC72C" },
  "California State University, Los Angeles": { primary: "#FFC72C", secondary: "#000000" },
  "California State University, Monterey Bay": { primary: "#003C71", secondary: "#A2AAAD" },
  "California State University, Northridge": { primary: "#C8102E", secondary: "#000000" },
  "California State University, Sacramento": { primary: "#00563F", secondary: "#FFCD00" },
  "California State University, San Bernardino": { primary: "#005596", secondary: "#A2AAAD" },
  "California State University, Stanislaus": { primary: "#990033", secondary: "#FDB827" },
  "Carnegie Mellon University": { primary: "#C41230", secondary: "#000000" },
  "Central Oregon Community College": { primary: "#003594", secondary: "#FFFFFF" },
  "Central Washington University": { primary: "#A10022", secondary: "#000000" },
  "Chapman University": { primary: "#9E1B32", secondary: "#000000" },
  "Claremont McKenna College": { primary: "#7A0026", secondary: "#FFCD00" },
  "Clemson University": { primary: "#F66733", secondary: "#522D80" },
  "Colorado College": { primary: "#CFB87C", secondary: "#000000" },
  "Colorado School of Mines": { primary: "#92252A", secondary: "#9D9CA1" },
  "Colorado State University": { primary: "#1E4D2B", secondary: "#C8C372" },
  "Colorado State University Pueblo": { primary: "#003594", secondary: "#FFB81C" },
  "Columbia University": { primary: "#9BCBEB", secondary: "#FFFFFF" },
  "Concordia University Irvine": { primary: "#000080", secondary: "#FFD700" },
  "Cornell University": { primary: "#B31B1B", secondary: "#FFFFFF" },
  "Cornish College of the Arts": { primary: "#000000", secondary: "#FFFFFF" },
  "Dartmouth College": { primary: "#00693E", secondary: "#FFFFFF" },
  "Dominican University of California": { primary: "#003B49", secondary: "#FFC72C" },
  "Duke University": { primary: "#003087", secondary: "#FFFFFF" },
  "Eastern Washington University": { primary: "#A10022", secondary: "#FFFFFF" },
  "Emory University": { primary: "#012169", secondary: "#B58500" },
  "Evergreen State College": { primary: "#005844", secondary: "#FFC627" },
  "Florida": { primary: "#0021A5", secondary: "#FA4616" },
  "Florida State University": { primary: "#782F40", secondary: "#CEB888" },
  "Fort Lewis College": { primary: "#00205B", secondary: "#FDB927" },
  "Fresno Pacific University": { primary: "#660066", secondary: "#FFC72C" },
  "George Fox University": { primary: "#003B5C", secondary: "#FFC72C" },
  "Georgetown University": { primary: "#041E42", secondary: "#8D817B" },
  "Georgia": { primary: "#BA0C2F", secondary: "#000000" },
  "Georgia Tech": { primary: "#B3A369", secondary: "#003057" },
  "Gonzaga University": { primary: "#041E42", secondary: "#A52638" },
  "Grand Canyon University": { primary: "#522398", secondary: "#807F84" },
  "Harvard University": { primary: "#A51C30", secondary: "#FFFFFF" },
  "Harvey Mudd College": { primary: "#FFC700", secondary: "#000000" },
  "Holy Names University": { primary: "#003594", secondary: "#FFC72C" },
  "Humboldt State University": { primary: "#0D381F", secondary: "#FFC72C" },
  "Idaho State University": { primary: "#F47820", secondary: "#000000" },
  "Indiana": { primary: "#990000", secondary: "#EEEDEB" },
  "Iowa": { primary: "#000000", secondary: "#FFCD00" },
  "Iowa State": { primary: "#C8102E", secondary: "#F1BE48" },
  "Kansas": { primary: "#0051BA", secondary: "#E8000D" },
  "Kansas State": { primary: "#512888", secondary: "#FFFFFF" },
  "Kentucky": { primary: "#0033A0", secondary: "#FFFFFF" },
  "Lane Community College": { primary: "#00529B", secondary: "#FFFFFF" },
  "Lewis & Clark College": { primary: "#F47B20", secondary: "#000000" },
  "Linfield University": { primary: "#5C0F8B", secondary: "#FFFFFF" },
  "Louisville": { primary: "#AD0000", secondary: "#000000" },
  "Loyola Marymount University": { primary: "#8E0028", secondary: "#00295B" },
  "LSU": { primary: "#461D7C", secondary: "#FDD023" },
  "Marquette": { primary: "#003366", secondary: "#FFCC00" },
  "Maryland": { primary: "#E03A3E", secondary: "#FFD520" },
  "Memphis": { primary: "#003E7E", secondary: "#8E9089" },
  "Menlo College": { primary: "#FF6600", secondary: "#000080" },
  "Miami (FL)": { primary: "#F47321", secondary: "#005030" },
  "Michigan": { primary: "#00274C", secondary: "#FFCB05" },
  "Michigan State": { primary: "#18453B", secondary: "#FFFFFF" },
  "Mills College": { primary: "#A52F47", secondary: "#FFFFFF" },
  "Minnesota": { primary: "#7A0019", secondary: "#FFCC33" },
  "Mississippi State": { primary: "#660000", secondary: "#FFFFFF" },
  "Missouri": { primary: "#F1B82D", secondary: "#000000" },
  "Montana State University": { primary: "#003875", secondary: "#FCC629" },
  "NC State": { primary: "#CC0000", secondary: "#000000" },
  "Nebraska": { primary: "#E41C38", secondary: "#FFFFFF" },
  "New Mexico Highlands University": { primary: "#522D80", secondary: "#FFFFFF" },
  "New Mexico State University": { primary: "#8C0B42", secondary: "#FFFFFF" },
  "North Carolina": { primary: "#7BAFD4", secondary: "#FFFFFF" },
  "Northwestern University": { primary: "#4E2A84", secondary: "#FFFFFF" },
  "Notre Dame de Namur University": { primary: "#000080", secondary: "#FFC72C" },
  "Occidental College": { primary: "#FF6E00", secondary: "#000000" },
  "Ohio State": { primary: "#BB0000", secondary: "#666666" },
  "Oklahoma": { primary: "#841617", secondary: "#FDF9D8" },
  "Oklahoma State": { primary: "#FF7300", secondary: "#000000" },
  "Ole Miss": { primary: "#CE1126", secondary: "#14213D" },
  "Oregon State University": { primary: "#DC4405", secondary: "#000000" },
  "Pacific": { primary: "#FF671F", secondary: "#000000" },
  "Pacific Lutheran University": { primary: "#000000", secondary: "#FFC72C" },
  "Pacific University": { primary: "#A6192E", secondary: "#000000" },
  "Penn": { primary: "#990000", secondary: "#01256E" },
  "Pennsylvania State University": { primary: "#041E42", secondary: "#FFFFFF" },
  "Pepperdine University": { primary: "#00205C", secondary: "#F47B20" },
  "Pittsburgh": { primary: "#003594", secondary: "#FFB81C" },
  "Pitzer College": { primary: "#F47B20", secondary: "#FFFFFF" },
  "Point Loma Nazarene University": { primary: "#003594", secondary: "#FFC72C" },
  "Pomona College": { primary: "#0050AE", secondary: "#FFFFFF" },
  "Portland Community College": { primary: "#005B82", secondary: "#FFFFFF" },
  "Portland University": { primary: "#582C83", secondary: "#FFFFFF" },
  "Princeton University": { primary: "#FF6600", secondary: "#000000" },
  "Purdue": { primary: "#CEB888", secondary: "#000000" },
  "Rice University": { primary: "#00205B", secondary: "#C1C6C8" },
  "Rutgers University": { primary: "#CC0033", secondary: "#000000" },
  "Saint Mary's (CA)": { primary: "#06315B", secondary: "#DA0029" },
  "Saint Mary's College of California": { primary: "#06315B", secondary: "#DA0029" },
  "Saint Martin's University": { primary: "#971B2F", secondary: "#000000" },
  "San Diego": { primary: "#003B70", secondary: "#75BEE9" },
  "San Diego State": { primary: "#A6192E", secondary: "#000000" },
  "San Francisco": { primary: "#00543C", secondary: "#FDB927" },
  "San Francisco State University": { primary: "#231161", secondary: "#FFC629" },
  "San Jose State University": { primary: "#0055A2", secondary: "#E5A823" },
  "Santa Clara University": { primary: "#AA0000", secondary: "#000000" },
  "Scripps College": { primary: "#005844", secondary: "#FFFFFF" },
  "Seattle Pacific University": { primary: "#900028", secondary: "#FFFFFF" },
  "Seattle University": { primary: "#AA0000", secondary: "#FFFFFF" },
  "Simon Fraser University": { primary: "#A6192E", secondary: "#CC9A3D" },
  "Sonoma State University": { primary: "#003366", secondary: "#FFFFFF" },
  "South Carolina": { primary: "#73000A", secondary: "#000000" },
  "South Florida": { primary: "#006747", secondary: "#CFC493" },
  "Stanford University": { primary: "#8C1515", secondary: "#FFFFFF" },
  "Syracuse": { primary: "#F76900", secondary: "#000E54" },
  "TCU": { primary: "#4D1979", secondary: "#A3A9AC" },
  "Tennessee": { primary: "#FF8200", secondary: "#FFFFFF" },
  "Texas": { primary: "#BF5700", secondary: "#FFFFFF" },
  "Texas A&M": { primary: "#500000", secondary: "#FFFFFF" },
  "Texas Tech": { primary: "#CC0000", secondary: "#000000" },
  "UC Irvine": { primary: "#0064A4", secondary: "#FFD200" },
  "UC Santa Barbara": { primary: "#003660", secondary: "#FEBC11" },
  "UCF": { primary: "#000000", secondary: "#BA9B37" },
  "UCLA": { primary: "#2774AE", secondary: "#FFD100" },
  "University of Alaska Anchorage": { primary: "#005A43", secondary: "#FFCB05" },
  "University of Alaska Fairbanks": { primary: "#16607F", secondary: "#FFC72C" },
  "University of Arizona": { primary: "#AB0520", secondary: "#0C234B" },
  "University of California, Berkeley": { primary: "#003262", secondary: "#FDB515" },
  "University of California, Davis": { primary: "#022851", secondary: "#FFBF00" },
  "University of California, Irvine": { primary: "#0064A4", secondary: "#FFD200" },
  "University of California, Los Angeles": { primary: "#2774AE", secondary: "#FFD100" },
  "University of California, San Diego": { primary: "#182B49", secondary: "#FFCD00" },
  "University of California, Santa Barbara": { primary: "#003660", secondary: "#FEBC11" },
  "University of California, Santa Cruz": { primary: "#003C6C", secondary: "#FDC700" },
  "University of Chicago": { primary: "#800000", secondary: "#767676" },
  "University of Colorado Boulder": { primary: "#CFB87C", secondary: "#000000" },
  "University of Colorado Colorado Springs": { primary: "#CFB87C", secondary: "#000000" },
  "University of Denver": { primary: "#864142", secondary: "#A89968" },
  "University of Idaho": { primary: "#191F1F", secondary: "#F1B82D" },
  "University of La Verne": { primary: "#005A43", secondary: "#F58025" },
  "University of Maryland": { primary: "#E03A3E", secondary: "#FFD520" },
  "University of Michigan": { primary: "#00274C", secondary: "#FFCB05" },
  "University of Montana": { primary: "#7A0019", secondary: "#FFC72C" },
  "University of Nevada, Las Vegas": { primary: "#CF0A2C", secondary: "#666666" },
  "University of Nevada, Reno": { primary: "#003A70", secondary: "#807F84" },
  "University of New Mexico": { primary: "#BA0C2F", secondary: "#63666A" },
  "University of North Carolina at Chapel Hill": { primary: "#7BAFD4", secondary: "#FFFFFF" },
  "University of Notre Dame": { primary: "#0C2340", secondary: "#C99700" },
  "University of Oregon": { primary: "#154733", secondary: "#FEE123" },
  "University of Pennsylvania": { primary: "#990000", secondary: "#01256E" },
  "University of Puget Sound": { primary: "#73122E", secondary: "#FFFFFF" },
  "University of Redlands": { primary: "#7B0815", secondary: "#999A9D" },
  "University of San Diego": { primary: "#003B70", secondary: "#75BEE9" },
  "University of San Francisco": { primary: "#00543C", secondary: "#FDB927" },
  "University of Southern California": { primary: "#990000", secondary: "#FFC72C" },
  "University of Utah": { primary: "#CC0000", secondary: "#FFFFFF" },
  "University of Virginia": { primary: "#232D4B", secondary: "#F84C1E" },
  "University of Washington": { primary: "#4B2E83", secondary: "#B7A57A" },
  "University of Wyoming": { primary: "#492F24", secondary: "#FFC425" },
  "USC": { primary: "#990000", secondary: "#FFC72C" },
  "Utah State University": { primary: "#00263A", secondary: "#9C9A91" },
  "Vanderbilt University": { primary: "#000000", secondary: "#866D4B" },
  "Villanova": { primary: "#00205B", secondary: "#13B5EA" },
  "Virginia": { primary: "#232D4B", secondary: "#F84C1E" },
  "Virginia Tech": { primary: "#630031", secondary: "#CF4420" },
  "Wake Forest University": { primary: "#9E7E38", secondary: "#000000" },
  "Washington": { primary: "#4B2E83", secondary: "#B7A57A" },
  "Washington State University": { primary: "#981E32", secondary: "#5E6A71" },
  "Washington University in St. Louis": { primary: "#A51417", secondary: "#003F87" },
  "Weber State University": { primary: "#492365", secondary: "#FFC72C" },
  "Western Oregon University": { primary: "#A30F32", secondary: "#FFFFFF" },
  "Western Washington University": { primary: "#00338D", secondary: "#FFFFFF" },
  "West Virginia": { primary: "#002855", secondary: "#EAAA00" },
  "Whitman College": { primary: "#FFCC00", secondary: "#000000" },
  "Whittier College": { primary: "#522D80", secondary: "#FFD100" },
  "Whitworth University": { primary: "#9D2235", secondary: "#000000" },
  "Willamette University": { primary: "#CE1126", secondary: "#FFC72C" },
  "Wisconsin": { primary: "#C5050C", secondary: "#FFFFFF" },
  "Xavier": { primary: "#004B8D", secondary: "#9D9695" },
  "Yale University": { primary: "#00356B", secondary: "#FFFFFF" }
}

const DEFAULT_COLORS = { primary: '#475569', secondary: '#94a3b8' }

// Lookup function: tries exact match, then fuzzy fallback for variant names.
export function getSchoolColors(schoolName) {
  if (!schoolName) return DEFAULT_COLORS

  // 1. Exact match
  if (SCHOOL_COLORS[schoolName]) return SCHOOL_COLORS[schoolName]

  // 2. Fuzzy match: strip common suffixes and try again
  const normalized = schoolName
    .replace(/\b(University|College|of|the)\b/gi, '')
    .replace(/[,'.]/g, '')
    .trim()
    .replace(/\s+/g, ' ')
    .toLowerCase()

  for (const [key, colors] of Object.entries(SCHOOL_COLORS)) {
    const keyNormalized = key
      .replace(/\b(University|College|of|the)\b/gi, '')
      .replace(/[,'.]/g, '')
      .trim()
      .replace(/\s+/g, ' ')
      .toLowerCase()
    if (keyNormalized === normalized) return colors
    if (keyNormalized.startsWith(normalized) || normalized.startsWith(keyNormalized)) return colors
  }

  return DEFAULT_COLORS
}

export function isLightColor(hex) {
  if (!hex) return false
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  return (0.299 * r + 0.587 * g + 0.114 * b) > 180
}